from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import json, os

def generate_pdf():
    with open("output/report.json", "r", encoding="utf-8") as f:
        report = json.load(f)

    doc = SimpleDocTemplate("output/ContagionGrid_Report.pdf", pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('title', fontSize=22, fontName='Helvetica-Bold',
                                  textColor=colors.HexColor('#FF4444'), spaceAfter=6)
    story.append(Paragraph("ContagionGrid — Containment Report", title_style))
    story.append(Paragraph(f"City: {report['city']} | Disease: {report['disease'].upper()} | Origin: {report['outbreak_location']}", styles['Normal']))
    story.append(Spacer(1, 16))

    # Summary table
    summary_data = [
        ['Initial Cases', 'Peak Zone', 'Total Zones', 'Red Zones'],
        [
            str(report.get('initial_cases', 0)),
            report.get('peak_zone', '-'),
            str(len(report.get('containment_zones', []))),
            str(len([z for z in report.get('containment_zones', []) if z['level'] == 'red']))
        ]
    ]
    t = Table(summary_data, colWidths=[120, 120, 120, 120])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1d27')),
        ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f9f9f9')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTSIZE', (0,0), (-1,-1), 11),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f5f5f5')]),
    ]))
    story.append(t)
    story.append(Spacer(1, 16))

    # Immediate Actions
    story.append(Paragraph("Immediate Actions", ParagraphStyle('h2', fontSize=14,
                  fontName='Helvetica-Bold', spaceAfter=6, textColor=colors.HexColor('#333'))))
    for action in report.get('immediate_actions', []):
        story.append(Paragraph(f"• {action}", styles['Normal']))
    story.append(Spacer(1, 12))

    # Containment Zones
    story.append(Paragraph("Containment Zones", ParagraphStyle('h2', fontSize=14,
                  fontName='Helvetica-Bold', spaceAfter=6, textColor=colors.HexColor('#333'))))

    level_colors = {'red': '#FF4444', 'orange': '#FF9900', 'yellow': '#FFD700'}
    for zone in report.get('containment_zones', []):
        color = colors.HexColor(level_colors.get(zone['level'], '#888888'))
        story.append(Paragraph(
            f"<b>{zone['name']}</b> — <font color='{level_colors.get(zone['level'], '#888')}'>{zone['level'].upper()}</font>",
            styles['Normal']
        ))
        for r in zone.get('restrictions', []):
            story.append(Paragraph(f"  • {r}", styles['Normal']))
        story.append(Paragraph(f"  <i>Reason: {zone.get('reason','')}</i>", styles['Normal']))
        story.append(Spacer(1, 6))

    # Resources
    story.append(Spacer(1, 8))
    story.append(Paragraph("Resource Deployment", ParagraphStyle('h2', fontSize=14,
                  fontName='Helvetica-Bold', spaceAfter=6, textColor=colors.HexColor('#333'))))
    res_data = [['Zone', 'Doctors', 'Testing Kits', 'Ambulances']]
    for zone_name, res in report.get('resource_plan', {}).items():
        res_data.append([zone_name, str(res.get('doctors',0)),
                         str(res.get('testing_kits',0)), str(res.get('ambulances',0))])
    rt = Table(res_data, colWidths=[150, 100, 120, 110])
    rt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1d27')),
        ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ALIGN', (1,0), (-1,-1), 'CENTER'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f5f5f5')]),
    ]))
    story.append(rt)
    story.append(Spacer(1, 16))

    # Footer
    story.append(Paragraph(
        "Generated by ContagionGrid — Agentic Disease Containment AI | Lucknow, India",
        ParagraphStyle('footer', fontSize=9, textColor=colors.grey, alignment=1)
    ))

    doc.build(story)
    print("✅ PDF saved: output/ContagionGrid_Report.pdf")

if __name__ == "__main__":
    generate_pdf()